name: pythonmusic163comment # 工作流程的名称
 
on: # 什么时候触发
  push:  # 当有代码推送时触发
#  schedule:
#    - cron: '*/10 * * * *'  # 每5分钟触发一次
jobs:
  execute-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限：允许工作流写入仓库

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Execute Python script
      run: python script/main.py


    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-commit script changes [skip ci]"  # [skip ci] 防止某些情况下的循环触发
        git push origin main
